
<header class="header">
	<style type="text/css">
*, textarea, input[type="text"], input[type="password"], input[type="datetime"],
	input[type="datetime-local"], input[type="date"], input[type="month"],
	input[type="time"], input[type="week"], input[type="number"], input[type="email"],
	input[type="url"], input[type="search"], input[type="tel"], input[type="color"],
	.uneditable-input {
	padding: 3px;
	height: auto;
}
</style>
</header>
<form class="" action="" method="POST">
	<fieldset>
		<div id="legend">
			<legend class="">Autenticação</legend>
		</div>
        <?= (isset($mensagem)) ? $mensagem : ''?>
        <div class="control-group">
			<label class="control-label" for="email">E-mail</label>
			<div class="controls">
				<input type="text" id="username" name="email" placeholder=""
					class="input-xlarge">
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="password">Senha:</label>
			<div class="controls">
				<input type="password" id="password" name="senha" placeholder=""
					class="input-xlarge">
			</div>
		</div>


		<div class="control-group">
			<!-- Button -->
			<div class="controls">
				<button class="btn btn-success">Login</button>
			</div>
		</div>
	</fieldset>
</form>
